More detailed API key error
stripe/stripe-cli pull request #921
Opened 2022-07-25 16:29 UTC by tomelm

Noticed that we were swallowing config errors when returning API keys if something on the config-level was busted. We probably want that for general usage but I made this configurable depending on the log-level.

2022-07-25 16:35 UTC, gracegoo-stripe approved these changes

2022-07-26 17:09 UTC, mnorth-stripe requested changes
Thanks for making our CLI errors more actionable!

I think you could add one more assertion to the test and then it's ready to ship

2022-07-26 17:09 UTC, mnorth-stripe commented on pkg/config/profile_test.go
> +		assert.ErrorContains(t, err, `config.toml: no such file or directory`)
Sometimes these error messages change or vary (e.g., different linux distros) and I'd like us to have a very obvious and actionable signal if/when that happens.

Can we have an assertion somewhere that alerts us if neither of the two cases we know about today are met?

2025-04-01 22:54 UTC, tomer-stripe commented
Closing this, very old

2025-04-01 22:54 UTC, closed without merging